# Generated by Django 4.2.21 on 2025-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Hauptgericht', 'Hauptgericht'), ('Salat', 'Salat'), ('Dessert', 'Dessert'), ('Snack', 'Snack'), ('Getränke', 'Getränke'), ('Suppe', 'Suppe')], default='Hauptgericht', max_length=50),
        ),
    ]
