# Generated by Django 4.2.21 on 2025-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='myapp.recipe'),
        ),
    ]
