# Generated by Django 4.2.21 on 2025-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('main', 'Hauptgericht'), ('salad', 'Salat'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('drink', 'Getränk'), ('soup', 'Suppe')], default='main', max_length=50),
        ),
    ]
