# Generated by Django 4.2.21 on 2025-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipes/2025-04-25 14.23.40.jpg', upload_to='recipes/'),
        ),
    ]
