# Generated by Django 4.2.21 on 2025-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/default.jpg', null=True, upload_to='recipes/'),
        ),
    ]
